/*
 * File: app/view/ContactPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('UTalBus.view.ContactPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.contactpanel',

    config: {
        html: '</br>&nbspProyecto financiado por la Vicerrectoria de </br>&nbspDesarrollo Estudiantil (VDE)</br>&nbsp;Si tienes alguna sugerencia puedes enviar</br>&nbsp;un correo a: fastroza@alumnos.utalca.cl',
        itemId: 'contactPanel'
    },

    initialize: function() {
        this.callParent();
    }

});