/*
 * File: app/view/DevicePanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('UTalBus.view.DevicePanel', {
    extend: 'Ext.Panel',
    alias: 'widget.devicepanel',

    requires: [
        'Ext.Toolbar',
        'Ext.field.Text',
        'Ext.Button',
        'Ext.Map'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    type: 'hbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'textfield',
                        width: 200,
                        label: 'Velocidad:',
                        labelWidth: '48%',
                        labelWrap: true,
                        readOnly: true
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        height: 44,
                        itemId: 'mybutton5',
                        width: 118,
                        iconCls: 'info',
                        text: 'Detalles'
                    }
                ]
            },
            {
                xtype: 'map',
                docked: 'bottom',
                height: '90%',
                itemId: 'mymap',
                mapOptions: {
                    center: {
                        latitude: -35.001624,
                        longitude: -71.230127
                    },
                    zoom: 18,
                    disableDoubleClickZoom: true,
                    maxZoom: 18,
                    minZoom: 10,
                    disableDefaultUI: true,
                    draggable: false
                }
            }
        ],
        listeners: [
            {
                fn: 'onPanelTap',
                event: 'tap',
                delegate: '#mybutton5'
            },
            {
                fn: 'onPanelPainted',
                event: 'painted'
            },
            {
                fn: 'onPanelInitialize',
                event: 'initialize'
            }
        ]
    },

    onPanelTap: function(panel) {
        this.details.showBy(panel);
    },

    onPanelPainted: function(element, eOpts) {
        track_device = true;
        items = this.items;
        store = Ext.getStore("TrackpointsStore");
        store.getProxy().setUrl("http://gps.iccutal.cl/devices/"+device_record.get('id')+"/trackpoints.json");
        tracking_marker.setTitle(device_record.get('name'));
        store.load();

    },

    onPanelInitialize: function(component, eOpts) {
        velocity_field = this.items.getAt(0).getAt(0);
        this.details = Ext.create('UTalBus.view.DeviceDetails');
        details = this.details;

    },

    initialize: function() {
        this.callParent();
        tracking_extmap = this.items.getAt(1);
        geocoder = new google.maps.Geocoder();
        Ext.onReady(function() {
        tracking_marker = new google.maps.Marker({
        	map: tracking_extmap.getMap(),
        	title: "Vehicle",
            icon: "http://gps.iccutal.cl/bus.png"
        });
        });
    }

});