/*
 * File: app/view/DeviceDetails.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('UTalBus.view.DeviceDetails', {
    extend: 'Ext.Panel',
    alias: 'widget.devicedetails',

    requires: [
        'Ext.tab.Panel'
    ],

    config: {
        centered: true,
        height: 170,
        hidden: false,
        itemId: 'deviceDetails',
        width: 200,
        hideOnMaskTap: true,
        modal: true,
        items: [
            {
                xtype: 'tabpanel',
                docked: 'top',
                height: 150,
                items: [
                    {
                        xtype: 'container',
                        title: 'Locación',
                        html: '',
                        padding: 5
                    },
                    {
                        xtype: 'container',
                        title: 'Estado',
                        padding: 5
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();
        this.setLocation = function(html) {
            this.getAt(0).getAt(0).setHtml(html);
        };

        this.setState = function(html) {
            this.getAt(0).getAt(2).setHtml(html);
        };

        devicedetails = this;
    }

});