/*
 * File: app/view/HomePanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('UTalBus.view.HomePanel', {
    extend: 'Ext.Panel',
    alias: 'widget.homepanel',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'homePanel',
        padding: 10,
        styleHtmlContent: true,
        scrollable: 'vertical',
        tpl: [
            '<h1>UTalBus</h1>',
            '<h4>version 0.2</h4>',
            'Mejoras para la version 0.3',
            '<ul>',
            '<li>',
            'Lista de paraderos actualizada',
            '</li>',
            '<li>',
            'Estimación de llegada a cada paradero',
            '</li>',
            '</ul>',
            'Mejoras para la version 0.4',
            '<ul>',
            '<li>Estimación de llegada a posición actual (usando geolocalización del teléfono)',
            '</li>',
            '</ul>',
            'Puedes encontrar mas información del proyecto <a href="https://wiki.iccutal.cl/wiki/UTalGPS">aquí</a>',
            '</br>',
            '</br>',
            '(C) 2013 - Los Niches Initiative'
        ]
    },

    initialize: function() {
        this.callParent();
        this.setHtml(this.getTpl().applyTemplate(this));
    }

});