/*
 * File: app/view/ParaderoPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('UTalBus.view.ParaderoPanel', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Label',
        'Ext.Map'
    ],

    config: {
        items: [
            {
                xtype: 'label',
                docked: 'top',
                height: 21,
                html: '(Nombre)'
            },
            {
                xtype: 'map',
                height: 200,
                mapOptions: {
                    zoom: 18,
                    draggable: true,
                    disableDefaultUI: true
                }
            }
        ]
    },

    initialize: function() {
        this.callParent();
        this.items.getAt(0).setHtml("<h2>&nbsp;"+this.config.bus_stop.get('name')+"</h2>");
        map = this.items.getAt(1);
        map.setMapCenter({latitude: this.config.bus_stop.get('latitude'), longitude: this.config.bus_stop.get('longitude')});

    }

});