/*
 * File: app/view/ParaderosPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('UTalBus.view.ParaderosPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.paraderospanel',

    requires: [
        'Ext.carousel.Carousel',
        'Ext.XTemplate'
    ],

    config: {
        items: [
            {
                xtype: 'carousel',
                height: '100%',
                itemId: 'mycarousel',
                tpl: [
                    '{name}'
                ],
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            var store = Ext.getStore("ParaderosStore");
                            var fill_carousel = function(carousel, store) {
                                store.each(function(record) {
                                    var panel = new Ext.create("UTalBus.view.ParaderoPanel", {bus_stop: record});
                                    carousel.add(panel);
                                });
                            };
                            store.on("load", function ()
                            {
                                fill_carousel(this, store);
                            }, this);
                            if(store.loaded) {
                                fill_carousel(this, store);
                            }
                        },
                        event: 'initialize'
                    }
                ]
            }
        ]
    }

});